#!/usr/bin/perl -w
#Copyright (C) 2012  Gris Ge <cnfourt@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;

my $dst_folder = "/home/fge/Pictures/BackGround/Bing";
my $bing_url = 'http://www.bing.com/?mkt=en-US';
#my $bing_url = 'http://cn.bing.com/?mkt=zh-CN';

sub main() {
    my $index_content = `curl $bing_url 2>/dev/null`;
    my $image_url = $1 if $index_content =~ m|g_img={url:'([^']+)'|m;
    return undef unless defined $image_url;
    my $image_name = $1 if $image_url =~
    m|(?:%[a-f1-9]{2}){0,1}([a-zA-Z0-9][^/%]+)$|;
    return undef unless defined $image_name;
    $image_url = "http://www.bing.com/$image_url" if $image_url =~ m|^/|;
    my $file_name = "$dst_folder/$image_name";
    my $today_file_name = "$dst_folder/today.jpg";
    `wget -q $image_url -O $file_name`;
    print "New wallpaper from bing:     $file_name\n";
    system('find '. $dst_folder .' -mtime +30 -name \*.jpg -exec rm -v {} \;');
    system("ln -sf $file_name $today_file_name");
}

main();
