#!/bin/bash

# The workaround script for applying patch via git am.
# 'git am' does not check the subject of patches for ordering.

git am \
    $(perl -e '
        my @r = sort {
             `grep Subject: $a` cmp `grep Subject: $b`
        } @ARGV;
        print "@r"
    ' $1/cur/*)
