#!/usr/bin/perl -w
#Copyright (C) 2015  Gris Ge <cnfourt@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;

while(<>){
    if (m|<h([0-9]+) id="([^"]+)">(.+)</h|){
        next if $1 < 2;

        my $level = $1;
        my $link = $2;
        my $title = $3;
        $title =~ s|<[/]*code>|`|g;
        print " " x ($level - 2);
        print "* [$title]";
        print "(#$link)\n";
    }
}
