#!/bin/bash

ip link | egrep "(tun0)|(redhat0)" 1>/dev/null 2>/dev/null
if [ $? -ne 0 ];then
    logger -t $0 -i -- "INFO: mbsync cannot start withou VPN"
    exit 0
fi

LOG_FILE="/var/log/imap_rh.log"
PASSWD_FILE="~/.passwd/.rh_passwd"
COMMMAND="mbsync --verbose RH"
echo >> $LOG_FILE
date >> $LOG_FILE
echo >> $LOG_FILE
$COMMMAND 1>>$LOG_FILE 2>&1 &
disown
