#!/bin/bash

ip link | egrep "(tun0)|(redhat0)" 1>/dev/null 2>/dev/null
if [ $? -ne 0 ];then
    logger -t $0 -i -- "INFO: mbsync cannot start withou VPN"
    exit 0
fi

LOG_FILE="/var/log/imap_rh.log"
COMMMAND="mbsync --verbose RH"
echo >> $LOG_FILE
date >> $LOG_FILE
echo >> $LOG_FILE
if [ "CHK$(pidof mbsync)" == "CHK" ];then
    $COMMMAND 1>>$LOG_FILE 2>&1 &
    disown
else
    echo "mbsync is still running" >> $LOG_FILE
fi
