#!/bin/bash

PASSWD=`cat ~/.passwd/.rh_irc_pass`;

qdbus org.kde.konversation /irc org.kde.konversation.raw \
    "irc.devel.redhat.com" "PRIVMSG userserv :login fge $PASSWD"
sleep 5
qdbus org.kde.konversation /irc org.kde.konversation.raw \
    "irc.devel.redhat.com" "PRIVMSG nickserv :regain fge"
qdbus org.kde.konversation /irc org.kde.konversation.raw \
    "irc.devel.redhat.com" "/NICK fge"
qdbus org.kde.konversation /irc org.kde.konversation.raw \
    "irc.devel.redhat.com" "PRIVMSG chanserv :invite #ktd"
qdbus org.kde.konversation /irc org.kde.konversation.raw \
    "irc.devel.redhat.com" "JOIN #ktd"
