#!/usr/bin/python
import pyotp;
import os;

'''
#### Initial setup
yum install perl-MIME-Base32 python-pyotp -y
cat > base32.pl << "EOF"
#!/usr/bin/perl

use MIME::Base32 qw( RFC );

undef $/;  # in case stdin has newlines
$string = <STDIN>;

$encoded = MIME::Base32::encode($string);

print "$encoded\n";
EOF

chmod 755 base32.pl

dd if=/dev/random of=/tmp/key bs=1 count=20
mkdir ~/.passwd
chmod 700 ~/.passwd
cat /tmp/key | ./base32.pl > ~/.passwd/.token
cat /tmp/key | xxd -ps
# put this output to OTP server, "enroll TOTP Token", sha1, 30 seconds
rm -f /tmp/key
'''

base32_str_fd= open(os.getenv('HOME') + '/.passwd/.token', 'r');
base32_str= base32_str_fd.read().rstrip('\n');
print "%06d" % pyotp.TOTP(base32_str).now();
