#!/usr/bin/perl
#Copyright (C) 2012  Gris Ge <cnfourt@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;

my $download_folder = "$ENV{HOME}/Downloads";
my @file_ext_lists = ( 'avi', 'rm', 'rmvb', 'mkv','mp4', 'part','wmv');

sub call_smp($){
    my $file_path = shift;
    system("env DISPLAY=:0 smplayer -fullscreen -close-at-end \"$file_path\"");
}

sub find_latest_movie($){
    my $folder = shift;
    opendir my $fd_download, $folder
      or die "FAIL: Cannot open dir $folder: $!\n";
    my $latest_file;
    my $latest_time;
    foreach my $file_name ( readdir ($fd_download)){
        next if $file_name =~ /^\./;
        if ( -d "$folder/$file_name" ){
            opendir my $fd_level_2_folder, "$folder/$file_name"
              or die "FAIL: cannot open dir $folder/$file_name\n";
            foreach my $file_name_2 ( readdir ($fd_level_2_folder)){
                next unless -f "$folder/$file_name/$file_name_2";
                next unless grep { $file_name_2 =~ /\.$_$/i }
                  @file_ext_lists;
                my $tmp_time = (stat("$folder/$file_name/$file_name_2"))[9];
                if ($latest_time <= $tmp_time ){
                    $latest_file = "$folder/$file_name/$file_name_2";
                    $latest_time = $tmp_time;
                }
            }
        }
        next unless -f "$folder/$file_name";
        next unless grep { $file_name =~ /\.$_$/i } @file_ext_lists;
        my $tmp_time = (stat("$folder/$file_name"))[9];
        if ($latest_time <= $tmp_time ){
            $latest_file = "$folder/$file_name";
            $latest_time = $tmp_time;
        }
    }
    return "$latest_file";
}

sub main(){
    my $latest_movie = find_latest_movie($download_folder);
    print "$latest_movie\n";
    return undef unless $latest_movie;
    call_smp($latest_movie);
}
main;
