#!/bin/bash

if [ "CHK$KONSOLE_DBUS_SESSION" == "CHK" ];then
    exit 0
fi

OLD_FORMAT="%n"
QDBUS_COMMAND="qdbus org.kde.konsole $KONSOLE_DBUS_SESSION"

if [ "CHK$1" == "CHKset" ];then
    $QDBUS_COMMAND org.kde.konsole.Session.setTabTitleFormat 0 '' \
        1>/dev/null 2>/dev/null
    $QDBUS_COMMAND org.kde.konsole.Session.setTitle 0 "$2" \
        1>/dev/null 2>/dev/null
fi

if [ "CHK$1" == "CHKclean" ];then
    $QDBUS_COMMAND org.kde.konsole.Session.setTabTitleFormat 0 '%n' \
        1>/dev/null 2>/dev/null
fi

